export const sampleData = [
  {
    id: "GH4567",
    dueDate: "25th Aug 2021",
    name: "John Doe",
    amount: "",
    status: "pending",
    clientAddress: {
      street: "4729 Marion Street",
      city: "South Burlington",
      Area: "Vermont",
      country: "Vermont",
      zip: "05403",
    },
    billerAddress: {
      street: "221B Baker's Street",
      city: "London",
      Area: "England",
      country: "United Kingdom",
      zip: "SW1",
    },
    email: "someone@example.com",
    invoiceDate: "15th Aug 2021",
    paymentDate: "26th Jan 2022",
    items: [
      {
        itemName: "Bedsheets",
        quantity: "3",
        itemPrice: "30",
        totalItemPrice: "",
      },
      {
        itemName: "Pillows",
        quantity: "5",
        itemPrice: "10",
        totalItemPrice: "",
      },
    ],
  },
  {
    id: "GH5678",
    dueDate: "20th Sep 2022",
    name: "John Smith",
    amount: "",
    status: "paid",
    clientAddress: {
      street: "4729 Marion Street",
      city: "South Burlington",
      Area: "Vermont",
      country: "Vermont",
      zip: "05403",
    },
    billerAddress: {
      street: "221B Baker's Street",
      city: "London",
      Area: "England",
      country: "United Kingdom",
      zip: "SW1",
    },
    email: "someone@example.com",
    invoiceDate: "15th Aug 2021",
    paymentDate: "26th Jan 2022",
    items: [
      {
        itemName: "Bedsheets",
        quantity: "3",
        itemPrice: "30",
        totalItemPrice: "",
      },
      {
        itemName: "Chairs",
        quantity: "2",
        itemPrice: "25",
        totalItemPrice: "",
      },
    ],
  },
  {
    id: "GH6789",
    dueDate: "15th Jan 2022",
    name: "Carl Smith",
    amount: "",
    status: "pending",
    clientAddress: {
      street: "4729 Marion Street",
      city: "South Burlington",
      Area: "Vermont",
      country: "Vermont",
      zip: "05403",
    },
    billerAddress: {
      street: "221B Baker's Street",
      city: "London",
      Area: "England",
      country: "United Kingdom",
      zip: "SW1",
    },
    email: "someone@example.com",
    invoiceDate: "15th Aug 2021",
    paymentDate: "26th Jan 2022",
    items: [
      {
        itemName: "Bedsheets",
        quantity: "3",
        itemPrice: "30",
        totalItemPrice: "",
      },
      {
        itemName: "Tables",
        quantity: "2",
        itemPrice: "125",
        totalItemPrice: "",
      },
      {
        itemName: "Lamps",
        quantity: "6",
        itemPrice: "30",
        totalItemPrice: "",
      },
    ],
  },
  {
    id: "GH7890",
    dueDate: "20th Sep 2022",
    name: "John Smith",
    amount: "",
    status: "paid",
    clientAddress: {
      street: "4729 Marion Street",
      city: "South Burlington",
      Area: "Vermont",
      country: "Vermont",
      zip: "05403",
    },
    billerAddress: {
      street: "221B Baker's Street",
      city: "London",
      Area: "England",
      country: "United Kingdom",
      zip: "SW1",
    },
    email: "someone@example.com",
    invoiceDate: "15th Aug 2021",
    paymentDate: "26th Jan 2022",
    items: [
      {
        itemName: "Bedsheets",
        quantity: "3",
        itemPrice: "30",
        totalItemPrice: "",
      },
      {
        itemName: "Bedsheets",
        quantity: "3",
        itemPrice: "30",
        totalItemPrice: "",
      },
      {
        itemName: "Tables",
        quantity: "2",
        itemPrice: "125",
        totalItemPrice: "",
      },
      {
        itemName: "Lamps",
        quantity: "6",
        itemPrice: "30",
        totalItemPrice: "",
      },
    ],
  },
  {
    id: "GH8901",
    dueDate: "25th Aug 2021",
    name: "John Doe",
    amount: "",
    status: "pending",
    clientAddress: {
      street: "4729 Marion Street",
      city: "South Burlington",
      Area: "Vermont",
      country: "Vermont",
      zip: "05403",
    },
    billerAddress: {
      street: "221B Baker's Street",
      city: "London",
      Area: "England",
      country: "United Kingdom",
      zip: "SW1",
    },
    email: "someone@example.com",
    invoiceDate: "15th Aug 2021",
    paymentDate: "26th Jan 2022",
    items: [
      {
        itemName: "Bedsheets",
        quantity: "3",
        itemPrice: "30",
        totalItemPrice: "",
      },
    ],
  },
  {
    id: "GH9012",
    dueDate: "25th Mar 2020",
    name: "Jane Doe",
    amount: "",
    status: "paid",
    clientAddress: {
      street: "4729 Marion Street",
      city: "South Burlington",
      Area: "Vermont",
      country: "Vermont",
      zip: "05403",
    },
    billerAddress: {
      street: "221B Baker's Street",
      city: "London",
      Area: "England",
      country: "United Kingdom",
      zip: "SW1",
    },
    email: "someone@example.com",
    invoiceDate: "15th Aug 2021",
    paymentDate: "26th Jan 2022",
    items: [
      {
        itemName: "Tables",
        quantity: "2",
        itemPrice: "125",
        totalItemPrice: "",
      },
      {
        itemName: "Lamps",
        quantity: "6",
        itemPrice: "30",
        totalItemPrice: "",
      },
      {
        itemName: "TVs",
        quantity: "3",
        itemPrice: "200",
        totalItemPrice: "",
      },
    ],
  },
  {
    id: "GH9013",
    dueDate: "25th Mar 2020",
    name: "Jane Doe",
    amount: "",
    status: "paid",
    clientAddress: {
      street: "4729 Marion Street",
      city: "South Burlington",
      Area: "Vermont",
      country: "Vermont",
      zip: "05403",
    },
    billerAddress: {
      street: "221B Baker's Street",
      city: "London",
      Area: "England",
      country: "United Kingdom",
      zip: "SW1",
    },
    email: "someone@example.com",
    invoiceDate: "15th Aug 2021",
    paymentDate: "26th Jan 2022",
    items: [
      {
        itemName: "Tables",
        quantity: "2",
        itemPrice: "125",
        totalItemPrice: "",
      },
      {
        itemName: "Lamps",
        quantity: "6",
        itemPrice: "30",
        totalItemPrice: "",
      },
      {
        itemName: "ACs",
        quantity: "4",
        itemPrice: "300",
        totalItemPrice: "",
      },
    ],
  },
];
